#!/bin/bash

echo "Stopping the server..."
pkill gunicorn
sudo service nginx stop
sudo service memcached stop
tmux kill-session -t ctf 2> /dev/null

# Convert line ends
cd /vagrant
find . -type f -exec dos2unix {} \; &> /dev/null

echo "Starting the server..."
cd /vagrant/server
sudo service nginx start
sudo service memcached start
tmux new-session -s ctf -d 'tmux set remain-on-exit on && cd /vagrant/server && ./app.py run'