#!/bin/bash

source /etc/profile
echo $CTFDIR

echo "Stopping the server..."
pkill gunicorn
sudo service nginx stop
sudo service memcached stop
tmux kill-session -t ctf 2> /dev/null

# Convert line ends
cd $CTFDIR
find . -type f -exec dos2unix {} \; &> /dev/null
rm d2utmp*

echo "Starting the server..."
cd $CTFDIR/server
sudo service nginx start
sudo service memcached start
tmux new-session -s ctf -d "tmux set remain-on-exit on && cd $CTFDIR/server && ./app.py run"