#!/bin/bash

echo "Stopping the server..."
pkill gunicorn
sudo service nginx stop
sudo service memcached stop
tmux kill-session -t ctf 2> /dev/null

echo "Starting the server..."
cd /vagrant/server
sudo service nginx start
sudo service memcached start
tmux new-session -s ctf -d 'tmux set remain-on-exit on && gunicorn "app:app" -c /vagrant/scripts/gunicorn.py.ini'