"""empty message

Revision ID: 1025b7af6ea1
Revises: 64a5547e521c
Create Date: 2016-08-21 23:54:35.065350

"""

# revision identifiers, used by Alembic.
revision = '1025b7af6ea1'
down_revision = '64a5547e521c'

import sqlalchemy as sa
from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('restriction', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'restriction')
    ### end Alembic commands ###
