"""empty message

Revision ID: 348784d4864b
Revises: None
Create Date: 2016-07-15 23:05:23.105330

"""

# revision identifiers, used by Alembic.
revision = '348784d4864b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_activity_uaid'), 'activity', ['uaid'], unique=True)
    op.drop_index('uaid', table_name='activity')
    op.create_index(op.f('ix_config_key'), 'config', ['key'], unique=False)
    op.create_index(op.f('ix_files_fid'), 'files', ['fid'], unique=False)
    op.create_index(op.f('ix_login_tokens_sid'), 'login_tokens', ['sid'], unique=True)
    op.drop_index('sid', table_name='login_tokens')
    op.create_index(op.f('ix_pages_pgid'), 'pages', ['pgid'], unique=False)
    op.create_index(op.f('ix_problems_pid'), 'problems', ['pid'], unique=False)
    op.create_index(op.f('ix_programming_submissions_psid'), 'programming_submissions', ['psid'], unique=False)
    op.create_index(op.f('ix_solves_sid'), 'solves', ['sid'], unique=False)
    op.create_index(op.f('ix_team_invitations_rid'), 'team_invitations', ['rid'], unique=False)
    op.create_index(op.f('ix_teams_teamname_lower'), 'teams', ['teamname_lower'], unique=True)
    op.create_index(op.f('ix_teams_tid'), 'teams', ['tid'], unique=False)
    op.drop_index('teamname_lower', table_name='teams')
    op.create_index(op.f('ix_ticket_replies_trid'), 'ticket_replies', ['trid'], unique=False)
    op.create_index(op.f('ix_tickets_htid'), 'tickets', ['htid'], unique=False)
    op.create_index(op.f('ix_users_uid'), 'users', ['uid'], unique=True)
    op.create_index(op.f('ix_users_username_lower'), 'users', ['username_lower'], unique=True)
    op.drop_index('uid', table_name='users')
    op.drop_index('username_lower', table_name='users')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('username_lower', 'users', ['username_lower'], unique=True)
    op.create_index('uid', 'users', ['uid'], unique=True)
    op.drop_index(op.f('ix_users_username_lower'), table_name='users')
    op.drop_index(op.f('ix_users_uid'), table_name='users')
    op.drop_index(op.f('ix_tickets_htid'), table_name='tickets')
    op.drop_index(op.f('ix_ticket_replies_trid'), table_name='ticket_replies')
    op.create_index('teamname_lower', 'teams', ['teamname_lower'], unique=True)
    op.drop_index(op.f('ix_teams_tid'), table_name='teams')
    op.drop_index(op.f('ix_teams_teamname_lower'), table_name='teams')
    op.drop_index(op.f('ix_team_invitations_rid'), table_name='team_invitations')
    op.drop_index(op.f('ix_solves_sid'), table_name='solves')
    op.drop_index(op.f('ix_programming_submissions_psid'), table_name='programming_submissions')
    op.drop_index(op.f('ix_problems_pid'), table_name='problems')
    op.drop_index(op.f('ix_pages_pgid'), table_name='pages')
    op.create_index('sid', 'login_tokens', ['sid'], unique=True)
    op.drop_index(op.f('ix_login_tokens_sid'), table_name='login_tokens')
    op.drop_index(op.f('ix_files_fid'), table_name='files')
    op.drop_index(op.f('ix_config_key'), table_name='config')
    op.create_index('uaid', 'activity', ['uaid'], unique=True)
    op.drop_index(op.f('ix_activity_uaid'), table_name='activity')
    ### end Alembic commands ###
