"""empty message

Revision ID: 64a5547e521c
Revises: None
Create Date: 2016-07-19 02:47:02.345996

"""

# revision identifiers, used by Alembic.
revision = '64a5547e521c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('uaid', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('tid', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('pid', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('uaid')
    )
    op.create_index(op.f('ix_activity_uaid'), 'activity', ['uaid'], unique=True)
    op.create_table('config',
    sa.Column('cfid', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('cfid')
    )
    op.create_index(op.f('ix_config_key'), 'config', ['key'], unique=False)
    op.create_table('files',
    sa.Column('fid', sa.Integer(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('fid')
    )
    op.create_index(op.f('ix_files_fid'), 'files', ['fid'], unique=False)
    op.create_table('login_tokens',
    sa.Column('sid', sa.String(length=64), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('issued', sa.Integer(), nullable=True),
    sa.Column('expiry', sa.Integer(), nullable=True),
    sa.Column('ua', sa.String(length=128), nullable=True),
    sa.Column('ip', sa.String(length=16), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_index(op.f('ix_login_tokens_sid'), 'login_tokens', ['sid'], unique=True)
    op.create_table('pages',
    sa.Column('pgid', sa.Integer(), nullable=False),
    sa.Column('pvid', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('pgid')
    )
    op.create_index(op.f('ix_pages_pgid'), 'pages', ['pgid'], unique=False)
    op.create_table('problems',
    sa.Column('pid', sa.String(length=128), autoincrement=False, nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('hint', sa.Text(), nullable=True),
    sa.Column('grader', sa.Text(), nullable=True),
    sa.Column('autogen', sa.Boolean(), nullable=True),
    sa.Column('bonus', sa.Integer(), nullable=True),
    sa.Column('threshold', sa.Integer(), nullable=True),
    sa.Column('weightmap', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_index(op.f('ix_problems_pid'), 'problems', ['pid'], unique=False)
    op.create_table('programming_submissions',
    sa.Column('psid', sa.Integer(), nullable=False),
    sa.Column('pid', sa.String(length=128), nullable=True),
    sa.Column('tid', sa.Integer(), nullable=True),
    sa.Column('date', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('log', sa.Text(), nullable=True),
    sa.Column('submission_path', sa.Text(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('psid')
    )
    op.create_index(op.f('ix_programming_submissions_psid'), 'programming_submissions', ['psid'], unique=False)
    op.create_table('solves',
    sa.Column('sid', sa.Integer(), nullable=False),
    sa.Column('pid', sa.String(length=128), nullable=True),
    sa.Column('tid', sa.Integer(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=64), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.Column('flag', sa.Text(), nullable=True),
    sa.Column('bonus', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_index(op.f('ix_solves_sid'), 'solves', ['sid'], unique=False)
    op.create_table('team_invitations',
    sa.Column('rid', sa.Integer(), nullable=False),
    sa.Column('rtype', sa.Integer(), nullable=True),
    sa.Column('frid', sa.Integer(), nullable=True),
    sa.Column('toid', sa.Integer(), nullable=True),
    sa.Column('date', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('rid')
    )
    op.create_index(op.f('ix_team_invitations_rid'), 'team_invitations', ['rid'], unique=False)
    op.create_table('teams',
    sa.Column('tid', sa.Integer(), nullable=False),
    sa.Column('teamname', sa.String(length=64), nullable=True),
    sa.Column('teamname_lower', sa.String(length=64), nullable=True),
    sa.Column('school', sa.Text(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('observer', sa.Boolean(), nullable=True),
    sa.Column('finalized', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('tid'),
    sa.UniqueConstraint('teamname')
    )
    op.create_index(op.f('ix_teams_teamname_lower'), 'teams', ['teamname_lower'], unique=True)
    op.create_index(op.f('ix_teams_tid'), 'teams', ['tid'], unique=False)
    op.create_table('ticket_replies',
    sa.Column('trid', sa.Integer(), nullable=False),
    sa.Column('htid', sa.Integer(), nullable=True),
    sa.Column('date', sa.Integer(), nullable=True),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('trid')
    )
    op.create_index(op.f('ix_ticket_replies_trid'), 'ticket_replies', ['trid'], unique=False)
    op.create_table('tickets',
    sa.Column('htid', sa.Integer(), nullable=False),
    sa.Column('date', sa.Integer(), nullable=True),
    sa.Column('opened', sa.Boolean(), nullable=True),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('htid')
    )
    op.create_index(op.f('ix_tickets_htid'), 'tickets', ['htid'], unique=False)
    op.create_table('users',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('tid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('username_lower', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('utype', sa.Integer(), nullable=True),
    sa.Column('registertime', sa.Integer(), nullable=True),
    sa.Column('reset_token', sa.String(length=64), nullable=True),
    sa.Column('otp_secret', sa.String(length=16), nullable=True),
    sa.Column('otp_confirmed', sa.Boolean(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('email_token', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_uid'), 'users', ['uid'], unique=True)
    op.create_index(op.f('ix_users_username_lower'), 'users', ['username_lower'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username_lower'), table_name='users')
    op.drop_index(op.f('ix_users_uid'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tickets_htid'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_ticket_replies_trid'), table_name='ticket_replies')
    op.drop_table('ticket_replies')
    op.drop_index(op.f('ix_teams_tid'), table_name='teams')
    op.drop_index(op.f('ix_teams_teamname_lower'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_team_invitations_rid'), table_name='team_invitations')
    op.drop_table('team_invitations')
    op.drop_index(op.f('ix_solves_sid'), table_name='solves')
    op.drop_table('solves')
    op.drop_index(op.f('ix_programming_submissions_psid'), table_name='programming_submissions')
    op.drop_table('programming_submissions')
    op.drop_index(op.f('ix_problems_pid'), table_name='problems')
    op.drop_table('problems')
    op.drop_index(op.f('ix_pages_pgid'), table_name='pages')
    op.drop_table('pages')
    op.drop_index(op.f('ix_login_tokens_sid'), table_name='login_tokens')
    op.drop_table('login_tokens')
    op.drop_index(op.f('ix_files_fid'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_config_key'), table_name='config')
    op.drop_table('config')
    op.drop_index(op.f('ix_activity_uaid'), table_name='activity')
    op.drop_table('activity')
    ### end Alembic commands ###
