"""Add expiry time for states.

Revision ID: aca69d05f907
Revises: bc2288993bf3
Create Date: 2016-08-29 05:26:47.184862

"""

# revision identifiers, used by Alembic.
revision = 'aca69d05f907'
down_revision = 'bc2288993bf3'

from alembic import op
import sqlalchemy as sa


def upgrade():
### commands auto generated by Alembic - please adjust! ###
    op.add_column('o_auth_state', sa.Column('expire_time', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
### commands auto generated by Alembic - please adjust! ###
    op.drop_column('o_auth_state', 'expire_time')
    ### end Alembic commands ###
