"""empty message

Revision ID: bc2288993bf3
Revises: f271baf692c5
Create Date: 2016-08-28 04:15:22.209040

"""

# revision identifiers, used by Alembic.
revision = 'bc2288993bf3'
down_revision = 'f271baf692c5'

from alembic import op
import sqlalchemy as sa


def upgrade():
### commands auto generated by Alembic - please adjust! ###
    op.create_table('o_auth_state',
    sa.Column('sid', sa.String(length=64), nullable=False),
    sa.Column('access_token', sa.String(length=64), nullable=True),
    sa.Column('refresh_token', sa.String(length=64), nullable=True),
    sa.Column('redirect_uri', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_index(op.f('ix_o_auth_state_sid'), 'o_auth_state', ['sid'], unique=False)
    ### end Alembic commands ###


def downgrade():
### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_o_auth_state_sid'), table_name='o_auth_state')
    op.drop_table('o_auth_state')
    ### end Alembic commands ###
