"""empty message

Revision ID: f271baf692c5
Revises: 1025b7af6ea1
Create Date: 2016-08-26 03:03:11.145067

"""

# revision identifiers, used by Alembic.
revision = 'f271baf692c5'
down_revision = '1025b7af6ea1'

from alembic import op
import sqlalchemy as sa


def upgrade():
### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ctfcal_authorization', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ctfcal_authorization')
    ### end Alembic commands ###
